"""initial schema with not null constraints

Revision ID: 3c95c9a2afd0
Revises: 
Create Date: 2026-02-24 11:25:43.059837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c95c9a2afd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('violations', 'position_x',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('violations', 'position_y',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('violations', 'position_z',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('violations', 'distance_from_center',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('violations', 'owner_first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('violations', 'owner_last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('violations', 'owner_ssn',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('violations', 'owner_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('violations', 'owner_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('violations', 'owner_ssn',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('violations', 'owner_last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('violations', 'owner_first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('violations', 'distance_from_center',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('violations', 'position_z',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('violations', 'position_y',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('violations', 'position_x',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
