name: Run Pytest on Push to Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Add env variables here
    env:
      BASE_URL: "http://test"
      DATABASE_URL: "postgresql://user:pass@localhost/testdb"
      REDIS_URL: "redis://localhost:6379"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      DATABASE_URL_ASYNC: "postgresql+asyncpg://user:pass@localhost/testdb"
      DATABASE_URL_SYNC: "postgresql://user:pass@localhost/testdb"
      POSTGRES_DB: "testdb"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run tests
        run: |
          poetry run pytest

